id: IE20045AE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-09-26T07:23:20+00:00'
last_modified: '2022-06-13T12:53:55.714486+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ8040
  title: བཻ་ཌཱུརྱ་དཀར་པོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B844:
      image_group_id: I1KG12906
      title: ''
      total_pages: ''
      order: 1
      base_file: B844.txt
    EEDF:
      image_group_id: I1KG12907
      title: ''
      total_pages: ''
      order: 2
      base_file: EEDF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
